# RESTful 服务配置
server:
  mode: release # server mode: release, debug, test，默认 release
  healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
  middlewares: recovery,logger,secure,nocache,cors # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
  max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

# HTTP 配置
insecure:
  bind-address: x
  bind-port: x

# MySQL 数据库相关配置
sqlite:
  path: /root/goecm.db
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 2 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

#dockernet:
#  docker0: 172.17.0.1/16
#  docker_gwbridge: 172.18.0.1/16
#  macrowing: 10.1.0.0/24

# JWT 配置
jwt:
  realm: JWT
  key: dfVpOK8LZeJLZHYmHdb1VdyRrACKpqoo
  timeout: 24h
  max-refresh: 24h

log:
  name: goecm # Logger的名字
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: info # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号